version: '3'

services:
  #redis:
    #image: redis:latest
    #hostname: redis

  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PW=test2345

  home-app:
    restart: always
    container_name: home-app
    hostname: home-app
    build: .
    volumes:
      - .:/usr/src/app
    environment:
    - APP_SETTINGS=${APP_SETTINGS}
    - FLASK_APP=${FLASK_APP}
    - FLASK_ENV=${FLASK_ENV}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - SECRET_KEY=${SECRET_KEY}
    #- REDIS_URL=${REDIS_URL}
    - BROKER_URL=${BROKER_URL}

    ports:
      - '5001:5000'
    links:
      #- redis
      - rabbit
      - db
    depends_on:
      - db

  worker:
    build: .
    command: ./scripts/run_celery.sh
    volumes:
      - .:/usr/src/app
    links:
      - rabbit
      #- redis
    depends_on:
      - rabbit

  db:
    restart: always
    container_name: database
    hostname: database

    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
